#!/usr/bin/env bash
# This script tells the story of each user in /etc/passwd in the required format

while IFS=: read -r username password uid gid gecos homedir shell; do
    # Extract the first part of GECOS (before first comma) for user info
    user_info=$(echo "$gecos" | cut -d',' -f1)
    [ -z "$user_info" ] && user_info="$username"  # Fallback to username if empty
    
    # Format the output exactly as specified
    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" \
        "$username" "$gid" "$homedir" "$shell" "$uid" "$password" "$user_info"
done < /etc/passwd
