#!/usr/bin/env bash
# This script analyzes Apache logs to show IPs and status codes grouped by occurrence count

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{printf "%6d %s %s\n", $1, $2, $3}'
