#!/usr/bin/env bash
# This script groups Apache log visitors by IP and HTTP status code, and sorts them by number of occurrences

awk '{print $1, $9}' /var/log/apache2/access.log | sort | uniq -c | sort -rn | awk '{print $1, $2, $3}'
