#!/usr/bin/env bash
# This script displays numbers 1-20 with cultural bad luck annotations
# Uses case statement for specific number handling

number=1
while [ "$number" -le 20 ]
do
    echo "$number"
    case $number in
        4)
            echo "bad luck from China"  # 4 sounds like "death" in Chinese
            ;;
        9)
            echo "bad luck from Japan"  # 9 sounds like "suffering" in Japanese
            ;;
        17)
            echo "bad luck from Italy"  # 17 is considered unlucky in Italian culture
            ;;
    esac
    number=$((number + 1))
done
