#!/usr/bin/env bash
# Script that displays a list of currently running processes
# Shows all processes for all users, including those without TTY
# Displays in user-oriented format with process hierarchy

ps -eo user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,command --forest
